var adjectives = [
  "empty-headed",
  "animal",
  "daffy",
  "cheesy",
  "English",
  "tiny-brained",
  "illegitimate faced",
  "second hand",
  "nasty",
  "bucktoothed",
  "tedious",
  "cloth-eared",
  "flatulent",
  "swivel-eyed",
  "fornicating",
  "malodorous",
  "coffee-nosed",
  "tripe tasting",
  "snotty faced"
]
