var nouns = [
  "sons of a window-dresser",
  "bedwetting types",
  "wipers of other people's bottoms",
  "buggerfolk",
  "kniggets",
  "food-trough wiper",
  "pig-dogs",
  "son of a person",
  "so-called Arthur King",
  "trollop",
  "ponce",
  "poofter",
  "carriage ride participant",
  "pillock",
  "ratbag",
  "git",
  "prancer",
  "prancing pervert",
  "pram pusher",
  "heap of parrot droppings",
  "cheese eating surrender monkey",
  "muppet",
  "uphill gardener",
  "prat",
  "arsemonger",
  "tosser"
]
